import { parseGcodeText, parseDuration, gramsFromLength } from '../src/lib/slicer/parseGcode.ts'
import { calibrationFactors, type CalibrationRecord } from '../src/lib/slicer/types.ts'

const bambu = `; HEADER_BLOCK_START
; BambuStudio 02.02.01.60
; model printing time: 1h 12m 33s; total estimated time: 1h 20m 5s
; total layer number: 355
; total filament length [mm] : 7123.45,1024.1
; total filament weight [g] : 21.30,3.06
; filament_density = 1.24,1.26
; filament_type = PLA;PLA
; layer_height = 0.2
; nozzle_diameter = 0.4
; printer_model = Bambu Lab A1
; enable_support = 1
; HEADER_BLOCK_END
G28
; CONFIG_BLOCK_START
; total filament used [g] = 24.36
; estimated printing time (normal mode) = 1h 20m 5s
`
const prusa = `; generated by PrusaSlicer 2.8.1 on 2026-09-01
G28
; filament used [mm] = 5123.4
; filament used [cm3] = 12.32
; filament used [g] = 15.28
; filament cost = 0.38
; total filament used [g] = 15.28
; estimated printing time (normal mode) = 2h 3m 12s
; filament_density = 1.24
; filament_type = PETG
; layer_height = 0.15
; nozzle_diameter = 0.4
; printer_model = MK4S
; support_material = 0
`
const cura = `;FLAVOR:Marlin
;TIME:5432
;Filament used: 4.512m
;Layer height: 0.2
;MINX:10
;LAYER_COUNT:120
;Generated with Cura_SteamEngine 5.8.0
`
const show = (label: string, d: ReturnType<typeof parseGcodeText>) => console.log(label.padEnd(6), JSON.stringify({ src: d.source, t: d.printTimeSec, g: d.filamentGrams, mm: d.filamentMm, type: d.filamentType, dens: d.filamentDensity, printer: d.printerModel, lh: d.layerHeight, layers: d.layerCount, colors: d.filamentCount, sup: d.supportUsed, notes: d.notes }))
show('bambu', parseGcodeText(bambu, 'a.gcode'))
show('prusa', parseGcodeText(prusa, 'b.gcode'))
const c = parseGcodeText(cura, 'c.gcode'); show('cura', c)
const assert = (c: boolean, msg: string) => { if (!c) { console.error('FAIL:', msg); process.exit(1) } }
assert(Math.abs(gramsFromLength(1000, 1.24) - 2.98) < 0.05, 'gramsFromLength: 1 m 1.75 mm PLA ≈ 2.98 g')
console.log('cura gram (PLA 1.24):', gramsFromLength(c.filamentMm!, 1.24).toFixed(2), 'g')
console.log('süre:', ['1d 2h 3m 4s', '1h 20m 5s', '45m', '3661', '01:02:03', 'abc'].map((s) => `${s}→${parseDuration(s)}`).join(' | '))
assert(parseDuration('1d 2h 3m 4s') === 93784 && parseDuration('1h 20m 5s') === 4805 && parseDuration('45m') === 2700 && parseDuration('01:02:03') === 3723 && parseDuration('abc') == null, 'süre ayrıştırma')
const recs: CalibrationRecord[] = [
  { id: '1', date: '', printerId: 'a1', materialId: 'pla', presetKey: '', modelName: '', modelTimeSec: 3600, actualTimeSec: 4200, modelGrams: 20, actualGrams: 22 },
  { id: '2', date: '', printerId: 'a1', materialId: 'pla', presetKey: '', modelName: '', modelTimeSec: 1000, actualTimeSec: 1300, modelGrams: 10, actualGrams: 10.5 },
  { id: '3', date: '', printerId: 'a1', materialId: 'petg', presetKey: '', modelName: '', modelTimeSec: 1000, actualTimeSec: 2000, modelGrams: 10, actualGrams: 9 },
  { id: '4', date: '', printerId: 'a1', materialId: 'pla', presetKey: '', modelName: '', modelTimeSec: 100, actualTimeSec: 900, modelGrams: 1, actualGrams: 1 }, // uç değer
]
console.log('kalib a1+pla:', JSON.stringify(calibrationFactors(recs, 'a1', 'pla')))
console.log('kalib a1+asa (yazıcı geneli):', JSON.stringify(calibrationFactors(recs, 'a1', 'asa')))
console.log('kalib x2d (yok):', JSON.stringify(calibrationFactors(recs, 'x2d', 'pla')))
{ const f = calibrationFactors(recs, 'a1', 'pla'), g = calibrationFactors(recs, 'x2d', 'pla'); assert(f.samples > 0 && f.scope === 'printer+material' && f.timeFactor > 0 && g.samples === 0 && g.timeFactor === 1, 'kalibrasyon kapsamı') }
console.log('slicer: OK')
